version: '3.7'
services:
  #############
  ## CLIENT ##
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    networks:
        - webapp
    ports:
      - 3000:3000
    restart: always
    container_name: client
  ##############
  ## SERVER ##
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      networks:
        - webapp
    ports:
      - 5000:5000
    volumes:
      - ./server/node_modules:/app/node_modules
      - ./server/src:/app/src
    stdin_open: true
    restart: always
    container_name: server
  #############

