version: '3.7'
services:
  #############
  ## CLIENT ##
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:3000
    restart: always
    container_name: client
  ##############
  ## SERVER ##
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5500:5500
    container_name: server
  #############