version: '3.7'
services:
  #############
  ## CLIENT ##
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:8080
    restart: always
    container_name: client
  ##############
  ## SERVER ##
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    command: [ 'node', 'dist/main.js']
    container_name: server
  #############